name: Demo VM CI/CD

on:
  push:
    branches:
      - cicd
      - develop
  pull_request:
    types: [closed]
    branches:
      - develop
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_DEMO }}
          username: ${{ secrets.USERNAME_DEMO }}
          key: ${{ secrets.KEY_DEMO }}
          port: ${{ secrets.PORT_DEMO }}
          script: cd kanji_ecom && git checkout develop && git pull origin && docker-compose -f docker-compose.prod.yml up --build -d
